import argparse
import json
import logging
from collections import Counter
from pathlib import Path

import numpy as np

from ecg_arrhythmia.preprocessing.beat_extraction import (
    RR_FEATURE_DIM,
    SEQUENCE_LENGTH,
    WINDOW_SIZE,
)
from ecg_arrhythmia.streaming.onnx_contract import (
    create_onnx_session,
    validate_onnx_model,
    validate_session_contract,
)
from ecg_arrhythmia.streaming.onnx_sequence_classifier import ONNXSequenceClassifier
from ecg_arrhythmia.streaming.sequence_assembler import BeatSequence

logger = logging.getLogger(__name__)

DEFAULT_INPUT_MODEL_PATH = Path("artifacts/models/ecg_sequence_transformer.onnx")
DEFAULT_OUTPUT_MODEL_PATH = Path("artifacts/models/ecg_sequence_transformer_int8.onnx")
DEFAULT_REPORT_PATH = Path(
    "artifacts/results/deployment_evaluation/quantization/"
    "dynamic_int8_quantization_report.json"
)

BYTES_PER_MIB = 1024 * 1024


# ---------------------------------------------------------------------
#                          Size And Graph Helpers
# ---------------------------------------------------------------------


def file_size_mib(size_bytes: int) -> float:
    """Convert a byte count to mebibytes."""

    if size_bytes < 0:
        raise ValueError("File size must not be negative.")

    return size_bytes / BYTES_PER_MIB


def size_reduction_percentage(fp32_bytes: int, int8_bytes: int) -> float:
    """How much smaller the quantised file is, as a percentage of FP32."""

    if fp32_bytes <= 0:
        raise ValueError("FP32 model size must be positive.")

    if int8_bytes < 0:
        raise ValueError("INT8 model size must not be negative.")

    return (fp32_bytes - int8_bytes) / fp32_bytes * 100.0


def operator_type_counts(model_path: Path) -> dict[str, int]:
    """
    Count node operator types in an ONNX graph.

    Counts are keyed by op_type rather than node name, because node names
    are autogenerated and unstable while the operator mix is exactly what
    quantisation changes.
    """

    import onnx

    model = onnx.load(model_path)

    return dict(Counter(node.op_type for node in model.graph.node))


def summarise_operator_changes(
    fp32_counts: dict[str, int],
    int8_counts: dict[str, int],
) -> dict:
    """
    Describe how quantisation changed the operator mix.

    Quantised operator types are recognised by ONNX Runtime's naming
    convention for integer and quantise/dequantise kernels.
    """

    introduced = sorted(set(int8_counts) - set(fp32_counts))
    removed = sorted(set(fp32_counts) - set(int8_counts))

    reduced = sorted(
        op_type
        for op_type in set(fp32_counts) & set(int8_counts)
        if int8_counts[op_type] < fp32_counts[op_type]
    )

    quantised_present = sorted(
        op_type
        for op_type in int8_counts
        if "Integer" in op_type
        or "QuantizeLinear" in op_type
        or op_type.startswith("QLinear")
    )

    floating_point_remaining = sorted(
        op_type for op_type in int8_counts if op_type not in quantised_present
    )

    return {
        "operator_types_introduced": introduced,
        "operator_types_removed": removed,
        "operator_types_reduced": reduced,
        "quantised_operator_types_present": quantised_present,
        "remaining_floating_point_operator_types": floating_point_remaining,
    }


# ---------------------------------------------------------------------
#                             Quantisation
# ---------------------------------------------------------------------


# How the pre-quantisation pass ran. "full" is the complete recommended
# pass, "skip_symbolic_shape" drops only the sympy-based symbolic shape
# inference (which cannot follow this graph's reshape-into-Conv pattern)
# while keeping ORT graph optimisation and standard ONNX shape inference,
# and "none" means quantisation ran directly on the unprocessed graph.
PREPROCESSING_FULL = "full"
PREPROCESSING_SKIP_SYMBOLIC = "skip_symbolic_shape"
PREPROCESSING_NONE = "none"


def preprocess_model(
    input_model_path: Path,
    preprocessed_path: Path,
) -> tuple[str, str | None]:
    """
    Run ONNX Runtime's recommended pre-quantisation pass.

    Shape inference and graph optimisation happen here so they are
    separated from quantisation itself. The full pass is tried first; if
    its symbolic shape inference rejects the graph, the supported
    skip_symbolic_shape option retries with the remaining steps. Every
    failure is logged and reported rather than fatal, and the result
    still faces full contract validation afterwards.

    Returns the mode that succeeded and, when the full pass failed, the
    reason it failed, so the report can preserve it.
    """

    from onnxruntime.quantization.shape_inference import quant_pre_process

    try:
        # running quant_pre_process on an ONNX model is recommended before
        # quantization since it enhances the quality of the quantized model
        # by removing redundancies, checking tensor shape compatability, etc.
        quant_pre_process(
            input_model_path=input_model_path,
            output_model_path=preprocessed_path,
        )
    except Exception as error:
        full_error = f"{type(error).__name__}: {error}"
        logger.warning(
            "Full quant_pre_process failed for %s (%s); retrying with "
            "symbolic shape inference skipped",
            input_model_path,
            full_error,
        )
    else:
        # This runs only if the try block passes
        logger.info("Pre-processed model written to %s", preprocessed_path)
        return PREPROCESSING_FULL, None

    # We only get to this section of code if the except block runs.
    # A failed pass may leave a partial file behind. unlink
    # removes the partial file it may have written. If the file
    # does not exist it just moves on since missing_ok=True
    preprocessed_path.unlink(missing_ok=True)

    # We attempt to run the quant_pre_process again, this time we try a simpler,
    # safer optimization pass without using symbolic shape inference.
    try:
        quant_pre_process(
            input_model_path=input_model_path,
            output_model_path=preprocessed_path,
            skip_symbolic_shape=True,
        )
    except Exception:
        # No preprocessing is done in this case.
        logger.exception(
            "quant_pre_process failed for %s even with symbolic shape "
            "inference skipped; falling back to direct dynamic "
            "quantisation of the unprocessed graph",
            input_model_path,
        )
        preprocessed_path.unlink(missing_ok=True)
        return PREPROCESSING_NONE, full_error

    logger.info(
        "Pre-processed model written to %s (symbolic shape inference skipped)",
        preprocessed_path,
    )

    return PREPROCESSING_SKIP_SYMBOLIC, full_error


def validate_strict_shape_inference(model_path: Path) -> None:
    """
    Run standard ONNX shape inference in strict mode.

    This is a diagnostic guard for quantisation sources, separate from
    the production runtime checks. It proves the graph's declared shape
    metadata is internally consistent before the quantiser re-derives it.
    """

    import onnx

    # Load the original fp32 onnx model
    model = onnx.load(model_path)
    # Performs mathematical and dimensional validation. For example,
    # It ensures tensors have compatible shapes for operations like
    # matrix multiplication.
    onnx.shape_inference.infer_shapes(model, strict_mode=True)


def clean_value_info(source_path: Path, cleaned_path: Path) -> int:

    import onnx

    # Load the original or preprocessed model
    model = onnx.load(source_path)
    # Number of elements in the list
    removed = len(model.graph.value_info)

    # empties the entire value_info list
    del model.graph.value_info[:]
    # Saves this new model to cleaned_path
    onnx.save(model, cleaned_path)

    return removed


def quantize_model(
    input_model_path: Path = DEFAULT_INPUT_MODEL_PATH,
    output_model_path: Path = DEFAULT_OUTPUT_MODEL_PATH,
    keep_preprocessed_model: bool = False,
) -> dict:
    """
    Create and validate the dynamic INT8 candidate.

    The FP32 source is only ever read. The report dictionary records the
    configuration, both file sizes, the operator-mix change and every
    validation outcome.
    """

    from onnxruntime.quantization import QuantType, quantize_dynamic

    # We do not want to overwrite the FP32 ONNX model with the quantised
    # INT8 model.
    if input_model_path.resolve() == output_model_path.resolve():
        raise ValueError(
            "The quantised model must not overwrite the FP32 source: "
            f"both paths resolve to {input_model_path.resolve()}."
        )

    if not input_model_path.exists():
        raise FileNotFoundError(f"No FP32 ONNX model found at {input_model_path}")

    # Create the output path
    output_model_path.parent.mkdir(parents=True, exist_ok=True)

    # This is where we will save the preprocessed fp32 ONNX model
    # before quantisation
    preprocessed_path = output_model_path.with_name(
        output_model_path.stem + "_preprocessed_fp32.onnx"
    )
    cleaned_path = output_model_path.with_name(
        output_model_path.stem + "_cleaned_fp32.onnx"
    )

    # Although this step is included in quant_pre_process, we
    # can do it early to fail fast.
    validate_strict_shape_inference(input_model_path)
    logger.info("Original FP32 strict shape inference: passed")

    try:
        # returns whether full preprocessing occured, partial preprocessing,
        # or no preprocessing, along with its corresponding error.
        preprocessing_mode, full_preprocessing_error = preprocess_model(
            input_model_path,
            preprocessed_path,
        )
        # preprocessing_used will be True whether we did full or
        # partial preprocessing, False otherwise.
        preprocessing_used = preprocessing_mode != PREPROCESSING_NONE
        # we use the preprocessed model if preprocessing succeeded, else
        # we just use the original fp32 ONNX model path
        quantisation_base = (
            preprocessed_path if preprocessing_used else input_model_path
        )

        # The ONNX Runtime quantizer converts Gemm operations into MatMul
        # operations for optimization. To do this, it transposes the weights.
        # However, when it does this, it does not update the value_info metadata
        # that is attached to a model during exporting. So now the model contains
        # a contradiction The model now contains a contradiction: the actual
        # weight matrix might be a shape of (4, 128), but the metadata still
        # claims it is (128, 4). When the ONNX engine runs its strict shape
        # inference, it sees this contradiction and crashes. We can fix this
        # by removing the value_info metadata.
        value_info_entries_removed = clean_value_info(
            quantisation_base,
            cleaned_path,
        )
        logger.info(
            "Removed %d graph.value_info entries from the quantisation source",
            value_info_entries_removed,
        )

        # validate that the shapes align with this new model with the removed
        # metadata
        validate_strict_shape_inference(cleaned_path)
        logger.info("Cleaned FP32 strict shape inference: passed")

        logger.info("Quantising %s with dynamic QInt8 weights", cleaned_path)

        # We dynamically calculate the scale ofr inputs/activiations during
        # inference, this is dynamic quantization. Note, it may be worth
        # at a later date comparing static quantization
        quantize_dynamic(
            # Takes the clean model as input
            model_input=cleaned_path,
            # outputs the model to this path
            model_output=output_model_path,
            # converts weights from fp32 to int8
            weight_type=QuantType.QInt8,
        )
    finally:
        # Intermediates are removed even when a step above fails.
        if not keep_preprocessed_model:
            preprocessed_path.unlink(missing_ok=True)
            cleaned_path.unlink(missing_ok=True)

    # The candidate must clear the exact checks production applies.
    validate_onnx_model(output_model_path)
    structural_validation_passed = True

    session = create_onnx_session(output_model_path)
    validate_session_contract(session)
    contract_validation_passed = True

    providers = list(session.get_providers())

    # run one prediction on this int8 model
    smoke_inference_passed = run_smoke_inference(output_model_path)

    # Return the size of both models
    fp32_bytes = input_model_path.stat().st_size
    int8_bytes = output_model_path.stat().st_size

    fp32_counts = operator_type_counts(input_model_path)
    int8_counts = operator_type_counts(output_model_path)

    return {
        "quantisation": {
            "source_model_path": str(input_model_path),
            "quantised_model_path": str(output_model_path),
            "method": "onnxruntime post-training dynamic quantisation",
            "weight_type": "QInt8",
            "per_channel": False,
            "reduce_range": False,
            "preprocessing_used": preprocessing_used,
            "preprocessing_mode": preprocessing_mode,
            "preprocessing_fallback_used": preprocessing_mode != PREPROCESSING_FULL,
            "full_preprocessing_error": full_preprocessing_error,
            "source_strict_shape_inference_passed": True,
            "value_info_entries_removed": value_info_entries_removed,
            "cleaned_strict_shape_inference_passed": True,
            "preprocessed_model_kept": preprocessing_used and keep_preprocessed_model,
        },
        "size": {
            "fp32_bytes": fp32_bytes,
            "fp32_mib": file_size_mib(fp32_bytes),
            "int8_bytes": int8_bytes,
            "int8_mib": file_size_mib(int8_bytes),
            "reduction_bytes": fp32_bytes - int8_bytes,
            "reduction_mib": file_size_mib(fp32_bytes) - file_size_mib(int8_bytes),
            "reduction_percentage": size_reduction_percentage(
                fp32_bytes,
                int8_bytes,
            ),
        },
        "validation": {
            "structural_validation_passed": structural_validation_passed,
            "contract_validation_passed": contract_validation_passed,
            "smoke_inference_passed": smoke_inference_passed,
            "execution_providers": providers,
        },
        "operators": {
            "fp32_operator_counts": fp32_counts,
            "int8_operator_counts": int8_counts,
            **summarise_operator_changes(fp32_counts, int8_counts),
        },
    }


def run_smoke_inference(model_path: Path) -> bool:
    """
    Prove one prediction runs through the production classifier.

    A shape-correct synthetic sequence is enough: this checks execution,
    not accuracy or parity, which later sections measure properly.
    """

    # Load the quantised model
    classifier = ONNXSequenceClassifier(model_path)

    # Create a fake beat sequence
    sequence = BeatSequence(
        ecg=np.zeros((SEQUENCE_LENGTH, 1, WINDOW_SIZE), dtype=np.float64),
        rr=np.ones((SEQUENCE_LENGTH, RR_FEATURE_DIM), dtype=np.float64),
        target_peak_index=0,
        peak_indices=tuple(range(SEQUENCE_LENGTH)),
    )
    # Make a prediction
    event = classifier.predict(sequence)

    logger.info(
        "Smoke inference produced class %s through %s",
        event.predicted_label,
        classifier.providers[0],
    )

    return event.logits.shape == (4,)


# ---------------------------------------------------------------------
#                                 CLI
# ---------------------------------------------------------------------


def _write_json(payload: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        json.dump(payload, file, indent=4)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create the dynamic INT8 ONNX deployment candidate from the FP32 model."
        )
    )
    parser.add_argument(
        "--input-model-path",
        type=Path,
        default=DEFAULT_INPUT_MODEL_PATH,
    )
    parser.add_argument(
        "--output-model-path",
        type=Path,
        default=DEFAULT_OUTPUT_MODEL_PATH,
    )
    parser.add_argument(
        "--report-path",
        type=Path,
        default=DEFAULT_REPORT_PATH,
    )
    parser.add_argument(
        "--keep-preprocessed-model",
        action="store_true",
        help=(
            "Keep the intermediate pre-processed and value_info-cleaned "
            "FP32 models for debugging."
        ),
    )

    return parser.parse_args()


def main() -> None:
    logging.basicConfig(level=logging.INFO)

    # Extract cli arguments
    args = parse_args()

    # return quantisation, size, validation, and
    # operator metrics
    report = quantize_model(
        input_model_path=args.input_model_path,
        output_model_path=args.output_model_path,
        keep_preprocessed_model=args.keep_preprocessed_model,
    )

    # Write them to our report path
    _write_json(report, args.report_path)

    logger.info("Wrote quantisation report to %s", args.report_path)


if __name__ == "__main__":
    main()
